from crud.namalar_crud import create_namalar,read_namalar,update_namalar,delete_namalar
from crud.permanlar_crud import create_perman,update_pdf,read_permanlar,update_active,read_one,delete_permanlar
from crud.dictinory_crud import create_dictinary,delete_dictinary,update_dictinary,read_dict
from crud.kodeks_crud import create_kodeks,delete_kodeks,update_kodeks,read_kodeks
from crud.information_crud import create_information, delete_information, update_information, read_information